# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speech_types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='speech_types.proto',
  package='rokid.open.speech.v1',
  syntax='proto2',
  serialized_pb=_b('\n\x12speech_types.proto\x12\x14rokid.open.speech.v1*y\n\x0fSpeechErrorCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\x13\n\x0fUNAUTHENTICATED\x10\x02\x12\x15\n\x11\x43ONNECTION_EXCEED\x10\x03\x12\x15\n\x11RESOURCE_EXHASTED\x10\x04\x12\x08\n\x04\x42USY\x10\x05\x12\x0c\n\x08INTERNAL\x10\x06*2\n\x07ReqType\x12\t\n\x05START\x10\x00\x12\t\n\x05VOICE\x10\x01\x12\x07\n\x03\x45ND\x10\x02\x12\x08\n\x04TEXT\x10\x03*#\n\x05\x43odec\x12\x07\n\x03PCM\x10\x00\x12\x07\n\x03OPU\x10\x01\x12\x08\n\x04OPU2\x10\x02')
)

_SPEECHERRORCODE = _descriptor.EnumDescriptor(
  name='SpeechErrorCode',
  full_name='rokid.open.speech.v1.SpeechErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNAUTHENTICATED', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONNECTION_EXCEED', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESOURCE_EXHASTED', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BUSY', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL', index=5, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=44,
  serialized_end=165,
)
_sym_db.RegisterEnumDescriptor(_SPEECHERRORCODE)

SpeechErrorCode = enum_type_wrapper.EnumTypeWrapper(_SPEECHERRORCODE)
_REQTYPE = _descriptor.EnumDescriptor(
  name='ReqType',
  full_name='rokid.open.speech.v1.ReqType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VOICE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='END', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEXT', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=167,
  serialized_end=217,
)
_sym_db.RegisterEnumDescriptor(_REQTYPE)

ReqType = enum_type_wrapper.EnumTypeWrapper(_REQTYPE)
_CODEC = _descriptor.EnumDescriptor(
  name='Codec',
  full_name='rokid.open.speech.v1.Codec',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PCM', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPU', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPU2', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=219,
  serialized_end=254,
)
_sym_db.RegisterEnumDescriptor(_CODEC)

Codec = enum_type_wrapper.EnumTypeWrapper(_CODEC)
SUCCESS = 0
UNAUTHENTICATED = 2
CONNECTION_EXCEED = 3
RESOURCE_EXHASTED = 4
BUSY = 5
INTERNAL = 6
START = 0
VOICE = 1
END = 2
TEXT = 3
PCM = 0
OPU = 1
OPU2 = 2


DESCRIPTOR.enum_types_by_name['SpeechErrorCode'] = _SPEECHERRORCODE
DESCRIPTOR.enum_types_by_name['ReqType'] = _REQTYPE
DESCRIPTOR.enum_types_by_name['Codec'] = _CODEC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
