# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tts.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import speech_types_pb2 as speech__types__pb2

from speech_types_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='tts.proto',
  package='rokid.open.speech.v1',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\ttts.proto\x12\x14rokid.open.speech.v1\x1a\x12speech_types.proto\"]\n\nTtsRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04text\x18\x02 \x02(\t\x12\x11\n\tdeclaimer\x18\x03 \x01(\t\x12\r\n\x05\x63odec\x18\x04 \x01(\t\x12\x13\n\x0bsample_rate\x18\x05 \x01(\r\"}\n\x0bTtsResponse\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x35\n\x06result\x18\x02 \x02(\x0e\x32%.rokid.open.speech.v1.SpeechErrorCode\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\r\n\x05voice\x18\x04 \x01(\x0c\x12\x0e\n\x06\x66inish\x18\x05 \x01(\x08P\x00')
  ,
  dependencies=[speech__types__pb2.DESCRIPTOR,],
  public_dependencies=[speech__types__pb2.DESCRIPTOR,])




_TTSREQUEST = _descriptor.Descriptor(
  name='TtsRequest',
  full_name='rokid.open.speech.v1.TtsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='rokid.open.speech.v1.TtsRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='rokid.open.speech.v1.TtsRequest.text', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='declaimer', full_name='rokid.open.speech.v1.TtsRequest.declaimer', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='codec', full_name='rokid.open.speech.v1.TtsRequest.codec', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sample_rate', full_name='rokid.open.speech.v1.TtsRequest.sample_rate', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=148,
)


_TTSRESPONSE = _descriptor.Descriptor(
  name='TtsResponse',
  full_name='rokid.open.speech.v1.TtsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='rokid.open.speech.v1.TtsResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='rokid.open.speech.v1.TtsResponse.result', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='rokid.open.speech.v1.TtsResponse.text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='voice', full_name='rokid.open.speech.v1.TtsResponse.voice', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='finish', full_name='rokid.open.speech.v1.TtsResponse.finish', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=275,
)

_TTSRESPONSE.fields_by_name['result'].enum_type = speech__types__pb2._SPEECHERRORCODE
DESCRIPTOR.message_types_by_name['TtsRequest'] = _TTSREQUEST
DESCRIPTOR.message_types_by_name['TtsResponse'] = _TTSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TtsRequest = _reflection.GeneratedProtocolMessageType('TtsRequest', (_message.Message,), {
  'DESCRIPTOR' : _TTSREQUEST,
  '__module__' : 'tts_pb2'
  # @@protoc_insertion_point(class_scope:rokid.open.speech.v1.TtsRequest)
  })
_sym_db.RegisterMessage(TtsRequest)

TtsResponse = _reflection.GeneratedProtocolMessageType('TtsResponse', (_message.Message,), {
  'DESCRIPTOR' : _TTSRESPONSE,
  '__module__' : 'tts_pb2'
  # @@protoc_insertion_point(class_scope:rokid.open.speech.v1.TtsResponse)
  })
_sym_db.RegisterMessage(TtsResponse)


# @@protoc_insertion_point(module_scope)
