# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: speech.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import speech_types_pb2 as speech__types__pb2

from speech_types_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='speech.proto',
  package='rokid.open.speech.v2',
  syntax='proto2',
  serialized_pb=_b('\n\x0cspeech.proto\x12\x14rokid.open.speech.v2\x1a\x12speech_types.proto\"\x9e\x03\n\rSpeechOptions\x12(\n\x04lang\x18\x01 \x01(\x0e\x32\x1a.rokid.open.speech.v2.Lang\x12*\n\x05\x63odec\x18\x02 \x01(\x0e\x32\x1b.rokid.open.speech.v1.Codec\x12/\n\x08vad_mode\x18\x03 \x01(\x0e\x32\x1d.rokid.open.speech.v2.VadMode\x12\x14\n\x0cvend_timeout\x18\x04 \x01(\r\x12\x0e\n\x06no_nlp\x18\x05 \x01(\x08\x12\x1b\n\x13no_intermediate_asr\x18\x06 \x01(\x08\x12\r\n\x05stack\x18\x07 \x01(\t\x12\x15\n\rvoice_trigger\x18\x08 \x01(\t\x12\x13\n\x0bvoice_power\x18\t \x01(\x02\x12\x15\n\rtrigger_start\x18\n \x01(\r\x12\x16\n\x0etrigger_length\x18\x0b \x01(\r\x12\x15\n\rskill_options\x18\x0c \x01(\t\x12\x13\n\x0bvoice_extra\x18\r \x01(\t\x12\x11\n\tvad_begin\x18\x0e \x01(\r\x12\x1a\n\x12no_trigger_confirm\x18\x0f \x01(\x08\"\x9a\x01\n\rSpeechRequest\x12\n\n\x02id\x18\x01 \x02(\x05\x12+\n\x04type\x18\x02 \x02(\x0e\x32\x1d.rokid.open.speech.v1.ReqType\x12\r\n\x05voice\x18\x03 \x01(\x0c\x12\x0b\n\x03\x61sr\x18\x04 \x01(\t\x12\x34\n\x07options\x18\x05 \x01(\x0b\x32#.rokid.open.speech.v2.SpeechOptions\"\xdb\x01\n\x0eSpeechResponse\x12\n\n\x02id\x18\x01 \x02(\x05\x12,\n\x04type\x18\x02 \x02(\x0e\x32\x1e.rokid.open.speech.v2.RespType\x12\x35\n\x06result\x18\x03 \x02(\x0e\x32%.rokid.open.speech.v1.SpeechErrorCode\x12\x0b\n\x03\x61sr\x18\x04 \x01(\t\x12\x0b\n\x03nlp\x18\x05 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x06 \x01(\t\x12\r\n\x05\x65xtra\x18\x07 \x01(\t\x12\x12\n\nasr_scores\x18\x08 \x03(\x02\x12\x0b\n\x03vpr\x18\t \x01(\t*8\n\x08RespType\x12\x10\n\x0cINTERMEDIATE\x10\x00\x12\x0e\n\nASR_FINISH\x10\x01\x12\n\n\x06\x46INISH\x10\x02*\x16\n\x04Lang\x12\x06\n\x02ZH\x10\x00\x12\x06\n\x02\x45N\x10\x01*\x1f\n\x07VadMode\x12\t\n\x05LOCAL\x10\x00\x12\t\n\x05\x43LOUD\x10\x01P\x00')
  ,
  dependencies=[speech__types__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_RESPTYPE = _descriptor.EnumDescriptor(
  name='RespType',
  full_name='rokid.open.speech.v2.RespType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INTERMEDIATE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ASR_FINISH', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FINISH', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=854,
  serialized_end=910,
)
_sym_db.RegisterEnumDescriptor(_RESPTYPE)

RespType = enum_type_wrapper.EnumTypeWrapper(_RESPTYPE)
_LANG = _descriptor.EnumDescriptor(
  name='Lang',
  full_name='rokid.open.speech.v2.Lang',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ZH', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=912,
  serialized_end=934,
)
_sym_db.RegisterEnumDescriptor(_LANG)

Lang = enum_type_wrapper.EnumTypeWrapper(_LANG)
_VADMODE = _descriptor.EnumDescriptor(
  name='VadMode',
  full_name='rokid.open.speech.v2.VadMode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOCAL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOUD', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=936,
  serialized_end=967,
)
_sym_db.RegisterEnumDescriptor(_VADMODE)

VadMode = enum_type_wrapper.EnumTypeWrapper(_VADMODE)
INTERMEDIATE = 0
ASR_FINISH = 1
FINISH = 2
ZH = 0
EN = 1
LOCAL = 0
CLOUD = 1



_SPEECHOPTIONS = _descriptor.Descriptor(
  name='SpeechOptions',
  full_name='rokid.open.speech.v2.SpeechOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lang', full_name='rokid.open.speech.v2.SpeechOptions.lang', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='codec', full_name='rokid.open.speech.v2.SpeechOptions.codec', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vad_mode', full_name='rokid.open.speech.v2.SpeechOptions.vad_mode', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vend_timeout', full_name='rokid.open.speech.v2.SpeechOptions.vend_timeout', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='no_nlp', full_name='rokid.open.speech.v2.SpeechOptions.no_nlp', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='no_intermediate_asr', full_name='rokid.open.speech.v2.SpeechOptions.no_intermediate_asr', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stack', full_name='rokid.open.speech.v2.SpeechOptions.stack', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voice_trigger', full_name='rokid.open.speech.v2.SpeechOptions.voice_trigger', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voice_power', full_name='rokid.open.speech.v2.SpeechOptions.voice_power', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trigger_start', full_name='rokid.open.speech.v2.SpeechOptions.trigger_start', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trigger_length', full_name='rokid.open.speech.v2.SpeechOptions.trigger_length', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skill_options', full_name='rokid.open.speech.v2.SpeechOptions.skill_options', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voice_extra', full_name='rokid.open.speech.v2.SpeechOptions.voice_extra', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vad_begin', full_name='rokid.open.speech.v2.SpeechOptions.vad_begin', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='no_trigger_confirm', full_name='rokid.open.speech.v2.SpeechOptions.no_trigger_confirm', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=473,
)


_SPEECHREQUEST = _descriptor.Descriptor(
  name='SpeechRequest',
  full_name='rokid.open.speech.v2.SpeechRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='rokid.open.speech.v2.SpeechRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='rokid.open.speech.v2.SpeechRequest.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voice', full_name='rokid.open.speech.v2.SpeechRequest.voice', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='asr', full_name='rokid.open.speech.v2.SpeechRequest.asr', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='options', full_name='rokid.open.speech.v2.SpeechRequest.options', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=476,
  serialized_end=630,
)


_SPEECHRESPONSE = _descriptor.Descriptor(
  name='SpeechResponse',
  full_name='rokid.open.speech.v2.SpeechResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='rokid.open.speech.v2.SpeechResponse.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='rokid.open.speech.v2.SpeechResponse.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='rokid.open.speech.v2.SpeechResponse.result', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='asr', full_name='rokid.open.speech.v2.SpeechResponse.asr', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nlp', full_name='rokid.open.speech.v2.SpeechResponse.nlp', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='action', full_name='rokid.open.speech.v2.SpeechResponse.action', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='extra', full_name='rokid.open.speech.v2.SpeechResponse.extra', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='asr_scores', full_name='rokid.open.speech.v2.SpeechResponse.asr_scores', index=7,
      number=8, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vpr', full_name='rokid.open.speech.v2.SpeechResponse.vpr', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=633,
  serialized_end=852,
)

_SPEECHOPTIONS.fields_by_name['lang'].enum_type = _LANG
_SPEECHOPTIONS.fields_by_name['codec'].enum_type = speech__types__pb2._CODEC
_SPEECHOPTIONS.fields_by_name['vad_mode'].enum_type = _VADMODE
_SPEECHREQUEST.fields_by_name['type'].enum_type = speech__types__pb2._REQTYPE
_SPEECHREQUEST.fields_by_name['options'].message_type = _SPEECHOPTIONS
_SPEECHRESPONSE.fields_by_name['type'].enum_type = _RESPTYPE
_SPEECHRESPONSE.fields_by_name['result'].enum_type = speech__types__pb2._SPEECHERRORCODE
DESCRIPTOR.message_types_by_name['SpeechOptions'] = _SPEECHOPTIONS
DESCRIPTOR.message_types_by_name['SpeechRequest'] = _SPEECHREQUEST
DESCRIPTOR.message_types_by_name['SpeechResponse'] = _SPEECHRESPONSE
DESCRIPTOR.enum_types_by_name['RespType'] = _RESPTYPE
DESCRIPTOR.enum_types_by_name['Lang'] = _LANG
DESCRIPTOR.enum_types_by_name['VadMode'] = _VADMODE

SpeechOptions = _reflection.GeneratedProtocolMessageType('SpeechOptions', (_message.Message,), dict(
  DESCRIPTOR = _SPEECHOPTIONS,
  __module__ = 'speech_pb2'
  # @@protoc_insertion_point(class_scope:rokid.open.speech.v2.SpeechOptions)
  ))
_sym_db.RegisterMessage(SpeechOptions)

SpeechRequest = _reflection.GeneratedProtocolMessageType('SpeechRequest', (_message.Message,), dict(
  DESCRIPTOR = _SPEECHREQUEST,
  __module__ = 'speech_pb2'
  # @@protoc_insertion_point(class_scope:rokid.open.speech.v2.SpeechRequest)
  ))
_sym_db.RegisterMessage(SpeechRequest)

SpeechResponse = _reflection.GeneratedProtocolMessageType('SpeechResponse', (_message.Message,), dict(
  DESCRIPTOR = _SPEECHRESPONSE,
  __module__ = 'speech_pb2'
  # @@protoc_insertion_point(class_scope:rokid.open.speech.v2.SpeechResponse)
  ))
_sym_db.RegisterMessage(SpeechResponse)


# @@protoc_insertion_point(module_scope)
